---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/products/options
  label: Sizes
  match: "**/*"
- type: directory
  path: src/products
  label: Products
  create: all
  match: "**/*"
- type: heading
  label: Product Options
upload_dir: src/products/images
public_path: "/src/products/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
