---
label: Product
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: file
  name: image
  label: image
- type: text
  name: description
  label: description
- type: text
  name: sku
  label: sku
- name: variety
  type: select
  default: []
  config:
    required: false
    options:
    - Succulent
    - Cactus
    source:
      type: simple
      section: 
      file: 
      path: 
  label: variety
- type: text
  name: feature
  label: feature
- type: field_group_list
  name: priceBySize
  label: priceBySize
  fields:
  - type: text
    name: size
    label: size
  - type: number
    name: price
    label: price
- type: field_group
  name: plantCare
  label: plantCare
  fields:
  - type: text
    name: light
    label: light
  - type: text
    name: water
    label: water
